### ISSUE TITLE
[Feature Request] Extend Contract logic RENAME

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#137]
- Renaming assay identifier should also rename parent folder.
- Moving files, not stored in model to another assay might require to COPY a file from a to b.

@HLWeil @kMutagene @omaus

**Comment by HLWeil** [comment]
Yup rename might be necessary to rename the folders of assays/studies. Not sure whether there would still be a need for copy then.

**Comment by HLWeil** [comment]
https://github.com/nfdi4plants/ARCCommander/issues/212

**Comment by Freymaurer** [comment]
Rename specifically could be very important to handle soon:

https://github.com/nfdi4plants/ARCitect/issues/127
