### ISSUE TITLE
[Feature Request] ARCTables: Update input and output types against each other

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ARCtrl#150]
**Is your feature request related to a problem? Please describe.**
Before, all inputs in all ARCs were just "Source Name". Now they can be of any type (e.g. "Data", "Sample"...). We should have a function which checks, whether a node in one table also appears in another with another type and update it accordingly.

**Comment by Freymaurer** [comment]
This is done, right @HLWeil ?

**Comment by HLWeil** [comment]
Not yet
