### ISSUE TITLE
[Feature Request] Rename Namespaces to all start with ARCtrl

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#153]
- ARCtrl.ISA
- ARCtrl.ISA.Spreadsheet
- ARCtrl.CWL
- ....

**Comment by HLWeil** [comment]
Is it actually need/want to rename the namespaces too? For the sake of nuget packaging, renaming the projects should be enough:

```fsharp
#r "nuget: ARCtrl.ISA"

open ISA

ArcInvestigation.create("MyInvestigation") 
```

vs 

```fsharp
#r "nuget: ARCtrl.ISA"

open ARCtrl.ISA

ArcInvestigation.create("MyInvestigation") 
```

@Freymaurer @kMutagene
