### ISSUE TITLE
[Discussion] Rework Study and Assay registration

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ARCtrl#167]
## Filesystem
#160 
- Keep study and assay metadata ONLY in respective files
- Investigation file only contains investigation information
- ISA-XLSX standards has to be formalized

## Datamodel
- Study and assays both directly part of investigation object
- CRUD functions between assay and study only on Investigation level

**Comment by Freymaurer** [comment]
Added flag for investigation light
