### ISSUE TITLE
[Docs] Parsing priorities in unitized cvParam columns in table files

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ARCtrl#169]
The handling of unitized columns might be complex, as discussed in
https://github.com/nfdi4plants/user-stories/issues/9

Proposed parsing:

| Parameter [MyCategory] | Unit   | Term Source REF (ABC:00000) | Term Accession Number (ABC:00000) | > | Results In   |
|-----------------|--------|-----------------------------|-----------------------------------|----|--------------|
| 5               | MyUnit | DEF                         | DEF:12345                         | > | UnitizedCell |
| 5               |        | DEF                         | DEF:12345                         | > | UnitizedCell |
| 5               |        |                             |                                   | > | UnitizedCell |
|                 | MyUnit | DEF                         | DEF:12345                         | > | UnitizedCell |
|                 |        |                             |                                   | > | UnitizedCell |
| MyValue         | MyUnit | DEF                         | DEF:12345                         | > | UnitizedCell |
| MyValue         |        | DEF                         | DEF:12345                         | > | TermCell     |
| MyValue         |        |                             |                                   | > | TermCell     |

Additionally, to keep the `hasUnit` information of valueless columns. We might add the hasUnit to the Header.

**Comment by Freymaurer** [comment]
Add Term CompositeHeader tuple like:

````fsharp
type CompositeHeader = 
    // term
    | Component         of (OntologyAnnotation, hasUnit)
    | Characteristic    of (OntologyAnnotation, hasUnit)
    | Factor            of (OntologyAnnotation, hasUnit)
    | Parameter         of (OntologyAnnotation, hasUnit)
```

This required two more members. 

- `HasUnit: bool`
- `UpdateUnitized: bool -> CompositeHeader`

**Comment by Freymaurer** [comment]
Moved to developer docs 📚
