### ISSUE TITLE
[Feature Request] whitespace in assay folder name

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#217]
Not sure if we want this:

![image](https://github.com/nfdi4plants/ARCtrl/assets/39732517/a3036068-5fc8-49c1-ba17-5dbbcfd30cb1)

@HLWeil

**Comment by Freymaurer** [comment]
> In the test folders?

what? 😅

**Comment by Freymaurer** [comment]
Damn it, good question. I think this is a ARC created with ARCtrl and FileSystem paths for an assay with identifier "My Assay", which will, to my understanding, translate to on-disc directories

**Comment by HLWeil** [comment]
I see, maybe we can auto-update faulty user input when creating the object.

So: 
```fsharp
ArcAssay(Identifier = "My Assay")
```
will result in 
```
ArcAssay {Identifier = "My_Assay")
```

**Comment by Freymaurer** [comment]
This should be handled by checkValidIdentifiers or by any write functions. Closed until issues arise
