### ISSUE TITLE
[BUG] package.json specifies `Index.js` instead of correct `index.js`

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#264]
Pretty sure this was the reason npm build on linux failed. 

Which could also explain why @xiaoranzhou was not able to use docs specified import from `@nfdi4plants/arctrl`

Either change generated file to `Index.js` or update release_package.json entrypoint to `index.js`.

This is absolutly critical and should be fixed asap.

**Comment by xiaoranzhou** [comment]
Great to know that this is now under the scope.
I think this also affects building from source by using ARCitect main branch
