### ISSUE TITLE
[BUG-Python] Enum not hashable

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#267]
# Enum not hashable
 
enum types, specifically array/list are not hashable and cannot be used in combination with GroupBy or Maps. Maybe reflect .NET usage by using hashSeq function internally.

**Comment by HLWeil** [comment]
Is this issue still up to date? ISA core tests in python branch are all succeeding besides one caused by https://github.com/fable-compiler/Fable/issues/3717
