### ISSUE TITLE
[BUG-Javascript] npm package 'jsonschema' used in JsonValidation.js doesn't support "anyOf" propery

### ISSUE THREAD

**Issue by patrick-koenig** [nfdi4plants/ARCtrl#279]
The npm package 'jsonschema' used for JSON-Schema validation in `@nfdi4plants/arctrl/ISA/ISA.Json/Validation/JsonValidation.js` doesn't support "anyOf" propery, which is used in several JSON Schemas of ISA.

See https://github.com/tdegrunt/jsonschema/issues/388 for a corresponding issue raised in the Github repo of "jsonschema".

The affected JSON schemas of ISA are:
- factor_value_schema.json
- material_attribute_value_schema.json
- ontology_annotation_schema.json
- process_parameter_value_schema.json
- process_schema.json

As an alternative, you could try Ajv (https://ajv.js.org), as this officially supports "anyOf": https://ajv.js.org/json-schema.html#anyof

**Comment by Freymaurer** [comment]
Thanks for the feedback! I will look into this.

In case you want to help, you could adapt the following [file](https://github.com/nfdi4plants/ARCtrl/blob/main/src/ISA/ISA.Json/Validation/JsonValidation.js) to the new dependency. This would of great help!

**Comment by Freymaurer** [comment]
This was deemed not maintainable for the time being, we moves json schema validation to our unit tests to confirm our produced json is correct.
