### ISSUE TITLE
Increase performance ([BUG] ARCitect crashes on large isa files)

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCtrl#283]
**OS and framework information (please complete the following information):**
 - macOS, ARCitect v 0.0.21

**Describe the bug**

- ARCitect does not load anymore when selecting an ARC with a large isa.study.xlsx: 

[isa.study.xlsx](https://github.com/nfdi4plants/ARCitect/files/13646911/isa.study.xlsx)

**Comment by Freymaurer** [comment]
In .NET performance is already suboptimal with ~6s, but in JS it takes ~150s.

We identified the underlying issue in `ISA.Spreadsheet/ArcStudy.fs`. `ArcStudy.fromFsWorkbook`.

```fsharp
/// Reads an assay from a spreadsheet
static member fromFsWorkbook (doc:FsWorkbook) = 
    // Reading the "Assay" metadata sheet. Here metadata 
    let studyMetadata,assays = 

        match doc.TryGetWorksheetByName ArcStudy.metaDataSheetName with 
        | Option.Some sheet ->
            ArcStudy.fromMetadataSheet sheet
        | None ->  
            match doc.TryGetWorksheetByName ArcStudy.obsoleteMetaDataSheetName with 
            | Option.Some sheet ->
                ArcStudy.fromMetadataSheet sheet
            | None -> 
                printfn "Cannot retrieve metadata: Study file does not contain \"%s\" or \"%s\" sheet." ArcStudy.metaDataSheetName ArcStudy.obsoleteMetaDataSheetName
                ArcStudy.create(Identifier.createMissingIdentifier()),[]

    let sheets = doc.GetWorksheets() |> Seq.choose ArcTable.tryFromFsWorksheet // 5s
    if sheets |> Seq.isEmpty |> not then 
        let updatedTables = 
            ArcTables.updateReferenceTablesBySheets( // 150s
                (ArcTables studyMetadata.Tables),
                (ArcTables (ResizeArray sheets)),
                keepUnusedRefTables =  true
            )
        studyMetadata.Tables <- updatedTables.Tables
    studyMetadata ,assays
```

We require a test on the provided .xlsx file to verify performance optimisation.

**Comment by HLWeil** [comment]
@Brilator, could you recheck whether the performance increases could fix the `hanging` problem?

**Comment by Brilator** [comment]
I cannot see any difference on the ARC with large isa.study.xlsx
1. ARCitect v0.0.26 cannot open the ARC (loading forever)
2. ARC commander (v1.0) cannot really work on it either: `arc export`, `arc s list`, `arc a list` don't do much

**Comment by HLWeil** [comment]
Hmm. Could you link me to the ARC in question?

**Comment by HLWeil** [comment]
https://github.com/nfdi4plants/ARCCommander/releases/tag/v1.0.1
Should be around twice as fast. More updates coming (eventually)

**Comment by Freymaurer** [comment]
@HLWeil pls verify if issue persists
