### ISSUE TITLE
[Feature Request] Improve Tab to Json Conversion for Protocols and Processes

### ISSUE THREAD

**Issue by floWetzels** [nfdi4plants/ARCtrl#290]
When reading ISA-XLSX with the current ARCtrl version and then exporting to json-ld, the following problem concering names of of protocols an processes came up:
- Some protocols are generated without sensible ID/name when reading ISA-XLSX and then writing ISA-Json.
  - This happens when there is no `Protocol REF` column set, but other columns with protocol-exclusive information (e.g. protocol type or components) exist.
  - In this case, a protocol without a name is generated.
  - If there is no other property that can be used to derive an ID, a dummy ID will be used for the json-ld export, although the protocol contains non-empty information.
  - If there are more than one of such dummy protocols, they are merged into one dummy protocol in the flattened json-ld, which leads to inconsistencies.
- This is related to the question whether tables from different assays/studies can have non-unique names which lead to non-unique names for protocols/processes in the json (see https://github.com/nfdi4plants/ARC-specification/issues/66).
  - If table names don't have to be unique in an ARC, names have to be generated including assay/study names to yield valid jsonld.

**Comment by HLWeil** [comment]
Hey, I thought a bit about this. And I'm not sure whether it makes sense to give the protocol a name when there is no `Protocol REF` column set. By only adding this name in the presence of the column, the information gain from the existence of the name would be higher. Also the name should be retrievable from the process it is referenced by.

**Comment by Freymaurer** [comment]
Is this still up to date? @floWetzels
