### ISSUE TITLE
[Feature Request] Add Identifiers to ISA Assay

### ISSUE THREAD

**Issue by floWetzels** [nfdi4plants/ARCtrl#293]
Since the `ARCtrl.ISA.Json` datamodel extends core ISA anyway (e.g. an ISA `Person` in ARCtrl has an `ORCID` field, which does not exist in core ISA), I suggest to also add an `Identifier` field to the type `Assay`. This makes it easier to generate assay names, process names or protocol names when exporting to json-ld. If this field does not exist, the assay name has to be read from the file, which is possible in theory, but kind of breaks the concept of a self-contained encoder for the ISA.Json types. Furthermore, the necessity to read from files during the json export increases the complexity of the test setup.

The need for unifying the Assay and Study data structures w.r.t. identifiers and filenames has already been mentioned in the ARC sprecification: https://github.com/nfdi4plants/ARC-specification/issues/74

**Comment by Freymaurer** [comment]
There will be no object any more after the upcoming type unification! So this will be solved!
