### ISSUE TITLE
[Feature Request] Get write contracts only by changes.

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#309]
Add "dirty" flags to for all files. If a file was tocuhed it should return write contract.

**Comment by HLWeil** [comment]
I think the "getWriteContracts" function should return all write contracts. Even if not changed. But we could add a "getUpdateContracts" function, containing Update contracts only for the changed files.

**Comment by Freymaurer** [comment]
Exactly!

**Comment by HLWeil** [comment]
Related to #131
