### ISSUE TITLE
`ARCtrl.Path` shadows `System.IO.Path`

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/ARCtrl#398]
It is a common use case to open `System.IO` and use the `Path` class. However, `ARCtrl` also has a `Path` namespace, which shadows that class when opening both. I would suggest to prevent this by adding `RequireQualifiedAccess`.

```csharp
using ARCtrl;
using System.IO

Path.Combine("A", "B")
```

![image](https://github.com/nfdi4plants/ARCtrl/assets/21338071/face445a-d8bb-4061-afca-fcb4d9bab7d0)

**Comment by Freymaurer** [comment]
I renamed to `ARCtrl.ArcPathHelper` to still allow opening the module where needed.
