### ISSUE TITLE
[Feature Request] Support validation_packages.yml

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/ARCtrl#401]
This week will see a rollout of the new [Continuous Quality Control pipelines](https://github.com/nfdi4plants/ARC-specification/blob/main/ARC%20specification.md#mechanisms-for-arc-quality-control) on the DataHUB. This means that all ARCs using the old validation pipelines will need an update that moves them to using the new `validation_packages.yml` config file to opt-in for user-selected validation packages.

While [POCs of this exist across the ARCtrl stack]() and a manual migration guide will be uploaded, the ARCitect as the central tool must support this feature to some extent on launch. This will be on 2024-07-10, so time is of essence.

Therefore, ARCtrl needs:
- a Data model for validation packages
- Reader/Writer contracts for the file
- a Top-level API

Implementation details:

-  use the YAMLicious package and transpilable encoder/decoder logic for the yml file
-  a new `ARCtrl.ValidationPackages` project that contains a type model and low-level APIs

**Comment by kMutagene** [comment]
related: https://github.com/nfdi4plants/ARCitect/issues/211

**Comment by Freymaurer** [comment]
> Reader/Writer functions for the file 

~~functions~~ --> `Contract`s
