### ISSUE TITLE
[BUG] CompositeCell.Data toXX functions return failwith

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#402]
This issue is related to the following:

https://github.com/nfdi4plants/ARCtrl/blob/403081ee9648a87ffd0198baaebef025df51b006/src/Core/Table/CompositeCell.fs#L60

These are functions to generalize usage in tools. The implemented behavior is especially annoying as we allow transforming into freetext, which in return can be transformed to the other cell types. So now i need to do: `this.ToFreeTextCell().ToTermCell()`

**Comment by HLWeil** [comment]
In what scenario do you need to transform a data cell to a unitized or term cell? 

Any solution would IMO be very arbitrary and hard to predict as a user. Therefore I implemented it like this.

**Comment by Freymaurer** [comment]
In the same scenario i would use _.ToTermCell on a FreeText cell, any user requested converion between cell types.
