### ISSUE TITLE
[BUG] Spreadsheet parser enforces Data columns to have data cell

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#405]
CompositeColumn validates FreeText or Data CompositeCells for Data header, i cannot find any implications in the specification if Data columns MAY be freetext or MUST be data.

https://github.com/nfdi4plants/ARCtrl/blob/403081ee9648a87ffd0198baaebef025df51b006/src/Spreadsheet/AnnotationTable/CompositeColumn.fs#L73

For now i will change all logic to be output column MUST have data cells, This would require an update in CompositeColumn.validate function

**Comment by HLWeil** [comment]
So spreadsheet `writer` fails, if column contains Freetext Cell?

By specification, neither the `Data Format` nor the `Data Selector Format` columns are obligator (https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#inputs-and-outputs). Therefore FreeText (=Single string) should be fine.

**Comment by Freymaurer** [comment]
Per specification this might be true i am talking specifically about CompositeCell.Freetext added to Input/Output [Data] column.

In addition it seems that the autofill cells on table.AddColumn uses FreeText cells to autofill Data output columns.

**Comment by Freymaurer** [comment]
https://github.com/nfdi4plants/ARCtrl/blob/403081ee9648a87ffd0198baaebef025df51b006/src/Core/Table/ArcTableAux.fs#L210

This is a really annoying issue for datamap implementation in Swate. Not sure how to handle this
