### ISSUE TITLE
[Feature Request] CompositeCell.Data compatibility issues with existing logic

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#417]
# Issue

To interact between ARCtrl and Excel for example i use the `CompositeCell.GetContent()` function. This returns 1, 3 or 4 strings in an array. Which i also use to reverse the information into the correct cell type.

The new Data cell also returns 3 strings and makes the logic not unique anymore. Combined with a lot more settable fields i am unsure how to progress from this point:

![image](https://github.com/user-attachments/assets/4211631e-4dcd-4227-bce1-e5694eb360a8)

https://github.com/nfdi4plants/ARCtrl/blob/dc3822fd1fec14c6009425e618531adf8828119a/src/Core/Table/CompositeCell.fs#L50

# Requirements

* CompositeCell.GetContent must return an array of strings, which must have a unique number of strings according to CompositeCell type. 
* CompositeCell.GetContent must be fully reversible.
* Due to the same issue, Data cell information must always fully be written in excel. Currently it omits complete empty columns.

**Comment by HLWeil** [comment]
After discussion with @Freymaurer, this is not possible. 

Header is necessary to distinguish between the types of 3 cell Data content and e.g. Parameter content.
