### ISSUE TITLE
[Feature Request] Implementation and binding for base-level IO functions

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ARCtrl#443]
We want to integrate top-level ARC IO functionality like read and write directly into the main library. For this, we need a few base-level IO functions we can call in all frameworks.

These functions include:
- `ensureDirectory: string -> unit`
- `ensureFile: string -> unit`
- `getAllFilePaths: string -> string []`
- `readAllText: string -> string`
- `writeAllText: string -> string -> unit`
- `executeCommandWithResponse: string -> string -> string -> Result<string,string>` (for git?)

Xlsx read/write should be covered by FsSpreadsheet.NET/Js/Py

@Freymaurer @kappe-c

**Comment by Freymaurer** [comment]
> * writeAllText: string -> string -> string

What is the output? arg1: content as string, arg2: path. What is arg3?

**Comment by HLWeil** [comment]
> > * writeAllText: string -> string -> string
> 
> What is the output? arg1: content as string, arg2: path. What is arg3?

Idk 😅 , edited to unit

**Comment by HLWeil** [comment]
Done in #479
