### ISSUE TITLE
[BUG] RO-Crate of assay doesn't have processSequences anymore

### ISSUE THREAD

**Issue by feserm** [nfdi4plants/ARCtrl#459]
When reading an ARC from the XLSX representation and transforming it into a RO-Crate JSON, the assays do not have processSequences anymore. On a minor note, also the description of the investigation is missing for me.

`
"assays": [
                    {
                        "@id": "#assay/winter_2020_1",
                        "@type": [
                            "Assay"
                        ],
                        "additionalType": "Assay",
                        "identifier": "winter_2020_1",
                        "filename": "assays/winter_2020_1/isa.assay.xlsx",
                        "performers": [
                            {
                                "@id": "#EmptyPerson",
                                "@type": "Person",
                                "comments": [
                                    "{\"@id\":\"#Comment_Worksheet\",\"@type\":\"Comment\",\"name\":\"Worksheet\",\"@context\":{\"sdo\":\"http://schema.org/\",\"Comment\":\"sdo:Comment\",\"name\":\"sdo:name\",\"value\":\"sdo:text\"}}"
                                ],
                                "@context": {
                                    "sdo": "http://schema.org/",
                                    "Person": "sdo:Person",
                                    "orcid": "sdo:identifier",
                                    "firstName": "sdo:givenName",
                                    "lastName": "sdo:familyName",
                                    "midInitials": "sdo:additionalName",
                                    "email": "sdo:email",
                                    "address": "sdo:address",
                                    "phone": "sdo:telephone",
                                    "fax": "sdo:faxNumber",
                                    "comments": "sdo:disambiguatingDescription",
                                    "roles": "sdo:jobTitle",
                                    "affiliation": "sdo:affiliation"
                                }
                            }
                        ],
                        "@context": {
                            "sdo": "http://schema.org/",
                            "Assay": "sdo:Dataset",
                            "identifier": "sdo:identifier",
                            "additionalType": "sdo:additionalType",
                            "measurementType": "sdo:variableMeasured",
                            "technologyType": "sdo:measurementTechnique",
                            "technologyPlatform": "sdo:measurementMethod",
                            "dataFiles": "sdo:hasPart",
                            "performers": "sdo:creator",
                            "processSequences": "sdo:about",
                            "comments": "sdo:comment",
                            "filename": "sdo:url"
                        }
                    },
                    {
                        "@id": "#assay/winter_2020_2",
                        "@type": [
                            "Assay"
                        ],
                        "additionalType": "Assay",
                        "identifier": "winter_2020_2",
                        "filename": "assays/winter_2020_2/isa.assay.xlsx",
                        "performers": [
                            {
                                "@id": "#EmptyPerson",
                                "@type": "Person",
                                "comments": [
                                    "{\"@id\":\"#Comment_Worksheet\",\"@type\":\"Comment\",\"name\":\"Worksheet\",\"@context\":{\"sdo\":\"http://schema.org/\",\"Comment\":\"sdo:Comment\",\"name\":\"sdo:name\",\"value\":\"sdo:text\"}}"
                                ],
                                "@context": {
                                    "sdo": "http://schema.org/",
                                    "Person": "sdo:Person",
                                    "orcid": "sdo:identifier",
                                    "firstName": "sdo:givenName",
                                    "lastName": "sdo:familyName",
                                    "midInitials": "sdo:additionalName",
                                    "email": "sdo:email",
                                    "address": "sdo:address",
                                    "phone": "sdo:telephone",
                                    "fax": "sdo:faxNumber",
                                    "comments": "sdo:disambiguatingDescription",
                                    "roles": "sdo:jobTitle",
                                    "affiliation": "sdo:affiliation"
                                }
                            }
                        ],
`

**Comment by HLWeil** [comment]
Hey @feserm, which version of ARCtrl are you using, and which exact function do you call?

**Comment by feserm** [comment]
I formerly used 2.0.0a2, then updated to 2.0.1 (current version)

I just read the ARC Scaffold from File System using the methods as provided in https://github.com/nfdi4plants/ARCtrl/blob/main/docs/scripts_python/ARC.py. Afterwards, I call the to_rocrate_json_string() method to convert it.
`
    arc = read(base_path)
        
    rocrate = ARC.to_rocrate_json_string()(arc)
    with open('rocrate.json', 'w') as f:
       f.write(rocrate)
`

I found out that it can't read the worksheet 'Phenotyping' from the assays. I am now trying to fix the issue using the ARCitect to find out what causes this. From first look I see nothing that explains this to me immediately, as the study and its worksheet 'Growth' is loaded without any issues..

**Comment by feserm** [comment]
OK me again. I don't know what exactly I did wrong, but something seemingly was off in my particular ARC. What I did now to fix the issue is

1. to create a save copy of the assays, 
2. remove the assays from the ARC
3. add new assays using the ARCitect
4. copy the save copies of the assays into the new assays

I guess some reference was missing, idk. The weird thing to me is, that the RO-Crate contained the assays, but only the processSequence was missing.

**Comment by HLWeil** [comment]
Hmm, maybe there was something off with the xlsx sheet or the table.

So, in order for ARCtrl to parse the AnnotatonTable, it should be in a sheet containing a table element, whichs name has to start with "annotationTable". Maybe there was an issue there.

([specificaton](https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#annotation-table-sheets) just as reference)

**Comment by feserm** [comment]
Ok thanks. Then I will close the issue

**Comment by HLWeil** [comment]
You're welcome!

If this wasn't the cause for the issue afterall, feel free to reopen.
