### ISSUE TITLE
[Bug]: Cannot open isa.study.xlsx file in Excel (macos and windows)

### ISSUE THREAD

**Issue by Mestizia** [nfdi4plants/ARCtrl#462]
### What happened?

When opening isa.study.xlsx file in Excel after adding a study sheet and populating it with headers (both macos and windows) it prompts an alert message (see screenshots). 
To open the file, it has to "repair it". If you then save the changes, the sheet will not appear in arcitect any longer.
![image](https://github.com/nfdi4plants/ARCtrl/assets/8880988/aaa621a6-54a9-4510-9ca0-1f18c2a0cc29)
![image](https://github.com/nfdi4plants/ARCtrl/assets/8880988/c37516b6-4d4c-4700-a46f-c8bb4b50d652)

The changes automatically made are the following (macos):
![image](https://github.com/nfdi4plants/ARCtrl/assets/8880988/f9481651-6232-48df-b37d-54f3e03a21fc)

### Host

ARCitect

### Host Details

Excel version 16.78 (macos)

### Swate version

Swate Release Version v1.0.0-beta.04

**Comment by HLWeil** [comment]
Ah sry, overlooked this. I agree that this probably is caused by the missing body of the table.
