### ISSUE TITLE
[BUG] QSheet.Inputs returns sample if no string

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#80]
**Describe the bug && To Reproduce**
I create a QAssay from byte [] stream and covert to QSheet list as such:

```fsharp
let ms = new System.IO.MemoryStream(byteArray)
    let _,assay = ISADotNet.XLSX.AssayFile.Assay.fromStream ms
    let tables = QueryModel.QAssay.fromAssay assay
    tables.Sheets 
    |> List.map (fun (s: QSheet) -> s.Inputs) // map over QSheets
    |> printfn "[INPUTS]: %A"
```

This is the relevant file:
![image](https://user-images.githubusercontent.com/39732517/222426530-03633131-3154-48a1-92e6-e8779b0f7aa3.png)

And this the console output:
![image](https://user-images.githubusercontent.com/39732517/222426621-2a0ab719-82df-4485-8075-172b33205cb9.png)

As you can see the fields with value are correctly written as `Some Source`, whereas the other are written as `Some Sample`.

**Expected behavior**
All fields are `Some Source`.

**Comment by Freymaurer** [comment]
Same goes for QSheets created from `json`, via:

```fsharp
let assay = Assay.fromString jsonString
let tables = QueryModel.QAssay.fromAssay assay
// ... as above
```

**Comment by Freymaurer** [comment]
`s.Outputs` seems to be handled correctly:

![image](https://user-images.githubusercontent.com/39732517/222430047-58b0cb07-f80b-4174-acd7-92de89c36695.png)

**Comment by HLWeil** [comment]
Outdated.
