### ISSUE TITLE
[Feature Request] Clarify warnings & error messages

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/ARCtrl#82]
**Is your feature request related to a problem? Please describe.**
https://github.com/nfdi4plants/ISADotNet/blob/a06af930e4d3f9d3c49a7b07bb0496f927c4e6cc/src/ISADotNet.XLSX/AssayFile/Assay.fs#L133
would definitely be more useful if it contained the name of the Assay. In ARCs with dozens of Assays, it is annoying to check every Assay file one by one to find where it crashes.

**Comment by HLWeil** [comment]
Hey,

In general I agree that the errors could be improved. In this specific case though, I would take a different approach. The "Assay" sheet is not a necessity, but I would prohibit users from adding sheets to the assay that aren't either the `"Assay" metadata sheet` or a `isa process table`.

If the function you stated here fails, the error will be catched upstream and returned together with some contextualizing information.

**Comment by omaus** [comment]
> If the function you stated here fails, the error will be catched upstream and returned together with some contextualizing information.

It's `arcIO.NET.Investigation.fromArcFolder` that was used. It does not contextualize in terms of what path the file has or such. Maybe move this issue there?

**Comment by HLWeil** [comment]
This function, which is called in `arcIO.NET.Investigation.fromArcFolder`, does:

https://github.com/nfdi4plants/ISADotNet/blob/a06af930e4d3f9d3c49a7b07bb0496f927c4e6cc/src/ISADotNet.XLSX/AssayFile/Assay.fs#L175

**Comment by omaus** [comment]
Yes, but this does not happen if the Assay Metadatasheet is missing. Only appears when the ISA process is corrupted.

**Comment by omaus** [comment]
> But I would make the function fail if there was a sheet that's neither called "Assay" nor has a process table structure.

Dunno. Isn't that a thing we wanted to allow for the user? That they may have additional sheets where they can record their individual notes or anything?

> Oh and also if there is a Assay sheet which does not have the correct metadata sheet structure.

Agree on that.

**Comment by HLWeil** [comment]
Will close this for now. I think we can improve this on-demand for specific parts of the code.
