### ISSUE TITLE
[Fable] Issue on official fable docs

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#93]
Reminder to myself to add an how to to the official fable docs for using js files.

```xml
<EmbeddedResource Include="Validation\JsonValidation.js">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
</EmbeddedResource>
```

EmbeddedResource allows access to js file on same layer

![image](https://github.com/nfdi4plants/ISADotNet/assets/39732517/9890af51-c56c-4fe3-af8a-404cb3be403b)

```fsharp
// Fable.fs
[<ImportAll("./JsonValidation.js")>]
let JsonValidation: IValidate = jsNative
```

**Comment by HLWeil** [comment]
What's your status on this?

**Comment by Freymaurer** [comment]
Not done yet 😢
